print("                               Curriculum Vitae")
print("Nume Prenume:            Codreanu Alexandru")
print("Data Luna Anul Nasterii: 20.02.2005")
print("Locul Nasterii:          Chisinau Republica Moldova ")
print("E-mail:                  codreanualex.2005@gmail.com")
print("Telefon:                 +37368903127")
print("Nationalitate:           Moldovean")
print("Studii:                  Învăț la Liceul Mihai Eminescu")
print("Limbi straine:           Engleza nivel mediu")
print("                         Rusa nivel mediu") 
print("Hobiuri:                 Programare, Studierea stiintelor reale, sah")
print("Activitati extrascolare: Olimpiade fotbal")